### ISSUE TITLE
Sentry on prem 400 response status codes with relay

### ISSUE THREAD

**Issue by mitchfriedman** [getsentry/relay#658]
Hi, we have setup a relay service and we are trying to forward events to our on-prem sentry installation.

When sending test events (sentry-cli send-event -m 'A test event'), we see errors in relay logs like:

```
dropped event: could not send event to upstream
  caused by: upstream request returned error 400 Bad Request
```

and then when inspecting the logs on the sentry-web process, I see: 
```
Traceback (most recent call last):                                                                                                                                                                                      
File "/usr/local/lib/python2.7/site-packages/sentry/coreapi.py", line 308, in safely_load_json_string                                                                                                                 
obj = json.loads(json_string)                                                                                                                                                                                       
File "/usr/local/lib/python2.7/site-packages/sentry/utils/json.py", line 107, in loads 
return _default_decoder.decode(value)
File "/usr/local/lib/python2.7/site-packages/simplejson/decoder.py", line 373, in decoderaise JSONDecodeError("Extra data", s, end, len(s))
JSONDecodeError: Extra data: line 2 column 1 - line 4 column 1 (char 273 - 6049) 
```

We were previously going straight to sentry, and if I run the same command with the $SENTRY_DSN set to sentry, it works a s expected.

**Comment by jan-auer** [comment]
To use Relay with Sentry, you need to upgrade to Sentry 10. Recent versions of Relay are not compatible with older versions of Sentry onpremise and I highly recommend the upgrade.

**Comment by mitchfriedman** [comment]
We are using sentry 10, in particular, this sentry image: https://hub.docker.com/layers/getsentry/sentry/cc9f7d12f4dd7fc6dc3723876d46052655153143/images/sha256-83c5f359d425a21e27ea7150a2698ef9d7cd74ecf38b1a8207d524a5d763cb6b?context=explore

We tried upgrading to the most recent images (post v20.6.0, AFAICT), but these seem to introduce some changes that prevent _all_ events from being ingested into sentry with some errors that look like

```
[WARNING] django.security.csrf: Forbidden (CSRF cookie not set.)                               
```

and it looks like from the log lines that the sentry_dsn has been stripped from the URL.

**Comment by jan-auer** [comment]
Sorry about that, I actually meant `v20.6.0`. In addition to the CSRF warning, can you post more log context, particularly which request triggers this? 

A quick disclaimer: Running Relay in front of Sentry is still in development, and we haven't completed full integration for onpremise. There might be configuration missing, particularly around how requests are being routed.

In _20.6.0_, the sentry python server no longer handles event ingestion and most other requests made by Relay. Instead, those are handled by an internal Relay instance which runs as [`relay` container](https://github.com/getsentry/onpremise/blob/0a9f12404ad91f18f3a7add3893416bf285ea358/docker-compose.yml#L190).

**Comment by mitchfriedman** [comment]
For some context, we are deploying sentry on prem onto our k8s cluster with [this](https://github.com/sentry-kubernetes/charts) unofficial helm chart. The helm chart doesn't support relay yet.

On sentry 10 (before upgrading to `v20.6.0`, we could run `SENTRY_DSN=<my_dsn> sentry-cli send-event -m "test"` and events were ingested as expected, then once we upgraded running the exact same command results in the CSRF warning (which, maybe as you are suggesting, is expected since there is no relay in the on-prem cluster?)

Does this mean the only option is to figure out how to get a `relay` container running and configured properly, since relay doesn't work with previous versions of sentry and the latest sentry doesn't work with the old sentry clients sending events directly to the sentry python web server?
