### ISSUE TITLE
Peridocally crashed relay

### ISSUE THREAD

**Issue by admincheg** [getsentry/relay#849]
Hello.

Relay was builded from tag 20.10.1 by `cargo build --all-features` and time to time crashing with strange repeatable error:

```
Nov 23 17:10:53 sentry4 relay[5184]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:318:5
Nov 23 17:10:53 sentry4 relay[5184]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 23 17:10:53 sentry4 relay[5184]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:318:5
Nov 23 17:10:53 sentry4 relay[5184]: 2020-11-23T17:10:53Z [relay_server::actors::events] ERROR: error processing event: could not schedule project fetch
Nov 23 17:10:53 sentry4 relay[5184]:   caused by: Mailbox has closed
Nov 23 17:10:53 sentry4 relay[5184]: 2020-11-23T17:10:53Z [relay_server::actors::events] ERROR: error processing event: could not schedule project fetch
Nov 23 17:10:53 sentry4 relay[5184]:   caused by: Mailbox has closed
Nov 23 17:10:53 sentry4 relay[5184]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:318:5
Nov 23 17:10:53 sentry4 relay[5184]: 2020-11-23T17:10:53Z [relay_server::actors::events] ERROR: error processing event: could not schedule project fetch
Nov 23 17:10:53 sentry4 relay[5184]:   caused by: Mailbox has closed
Nov 23 17:10:53 sentry4 relay[5184]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:318:5
Nov 23 17:10:53 sentry4 relay[5184]: 2020-11-23T17:10:53Z [relay_server::actors::events] ERROR: error processing event: could not schedule project fetch
Nov 23 17:10:53 sentry4 relay[5184]:   caused by: Mailbox has closed
Nov 23 17:10:53 sentry4 relay[5184]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:318:5
Nov 23 17:10:53 sentry4 relay[5184]: 2020-11-23T17:10:53Z [relay_server::actors::events] ERROR: error processing event: could not schedule project fetch
Nov 23 17:10:53 sentry4 relay[5184]:   caused by: Mailbox has closed
Nov 23 17:10:53 sentry4 relay[5184]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:318:5
Nov 23 17:10:53 sentry4 relay[5184]: 2020-11-23T17:10:53Z [relay_server::actors::events] ERROR: error processing event: could not schedule project fetch
Nov 23 17:10:53 sentry4 relay[5184]:   caused by: Mailbox has closed
Nov 23 17:10:53 sentry4 relay[5184]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:318:5
Nov 23 17:10:53 sentry4 relay[5184]: 2020-11-23T17:10:53Z [relay_server::actors::events] ERROR: error processing event: could not schedule project fetch
Nov 23 17:10:53 sentry4 relay[5184]:   caused by: Mailbox has closed
```

All services, like kafka and clickhouse seems working. After restart relay working near 5 hours and crashing again with same errors.

Service config:
```
relay:
        mode: managed
        upstream: http://127.0.0.1:9000
        host: 127.0.0.1
        port: 3000
```

**Comment by untitaker** [comment]
Thanks for reporting,

It would be helpful to give us:

* the project config that Sentry returns to Relay (particularly the section `piiConfig`) as response to `/api/0/relays/projectconfigs/` or alternatively a screenshot of your Security & Privacy settings
* a sample event that makes relay crash, if the crash is repeatable with a particular event payload.

**Comment by admincheg** [comment]
Oh, sorry, wrong config attached. Current config below:

```
---
relay:
  upstream: "http://127.0.0.1:9001/"
  host: 127.0.0.1
  port: 3000
logging:
  level: INFO
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "127.0.0.1:9092"}
    - {name: "message.max.bytes", value: 50000000}
  redis: redis://127.0.0.1:6379
```

About "what event crash relay" I haven't answer, because we produce big bunch of events. All requests in nginx seems ok after relay crashing. Relay reply 200, but don't working. Logs near crash:

```
Nov 23 17:09:59 sentry4 snuba[27623]: 2020-11-23 17:09:59,553 Completed processing <Batch: 31 messages, open for 0.83 seconds>.
Nov 23 17:09:59 sentry4 sentry[25782]: 17:09:59 [INFO] batching-kafka-consumer: Flushing 4 items (from {(u'ingest-transactions', 0): [386L, 389L]}): forced:False size:False time:True
Nov 23 17:09:59 sentry4 sentry[25782]: 17:09:59 [INFO] batching-kafka-consumer: Worker flush took 14ms
Nov 23 17:10:00 sentry4 snuba[27623]: 2020-11-23 17:10:00,572 Completed processing <Batch: 6 messages, open for 1.02 seconds>.
Nov 23 17:10:01 sentry4 snuba[27623]: 2020-11-23 17:10:01,576 Completed processing <Batch: 1 message, open for 1.00 seconds>.
Nov 23 17:10:46 sentry4 sentry[25782]: 17:10:46 [INFO] batching-kafka-consumer: Flushing 2 items (from {(u'ingest-events', 0): [138959L, 138960L]}): forced:False size:False time:True
Nov 23 17:10:46 sentry4 sentry[25782]: 17:10:46 [INFO] batching-kafka-consumer: Worker flush took 11ms
Nov 23 17:10:47 sentry4 snuba[27623]: 2020-11-23 17:10:47,359 Completed processing <Batch: 2 messages, open for 1.02 seconds>.
Nov 23 17:10:53 sentry4 relay[5184]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:318:5
Nov 23 17:10:53 sentry4 relay[5184]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Nov 23 17:10:53 sentry4 relay[5184]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:318:5
Nov 23 17:10:53 sentry4 relay[5184]: 2020-11-23T17:10:53Z [relay_server::actors::events] ERROR: error processing event: could not schedule project fetch
Nov 23 17:10:53 sentry4 relay[5184]:   caused by: Mailbox has closed
Nov 23 17:10:53 sentry4 relay[5184]: 2020-11-23T17:10:53Z [relay_server::actors::events] ERROR: error processing event: could not schedule project fetch
Nov 23 17:10:53 sentry4 relay[5184]:   caused by: Mailbox has closed
Nov 23 17:10:53 sentry4 relay[5184]: thread '<unnamed>' panicked at 'assertion failed: replacement_chunks.is_empty()', relay-general/src/pii/processor.rs:318:5
Nov 23 17:10:53 sentry4 relay[5184]: 2020-11-23T17:10:53Z [relay_server::actors::events] ERROR: error processing event: could not schedule project fetch
Nov 23 17:10:53 sentry4 relay[5184]:   caused by: Mailbox has closed
```

Logs from nginx: [sentry.nginx.log](https://github.com/getsentry/relay/files/5589329/sentry.nginx.log)

Request payload of message before relay dying [payload.txt](https://github.com/getsentry/relay/files/5589374/payload.txt)

Screenshots with configuration:

![1606213278](https://user-images.githubusercontent.com/769936/100081423-e92fb500-2e3e-11eb-9e2f-08ac9c6da73c.png)
![1606213288](https://user-images.githubusercontent.com/769936/100081430-e9c84b80-2e3e-11eb-9ea4-36d097b3de88.png)

**Comment by untitaker** [comment]
can you take a screenshot of the Security & Privacy in the project settings too? Surely there must be something configured if `pii/processor.rs` runs.

**Comment by admincheg** [comment]
Em, last two screenshots created from Settings -> Security & Privacy.

**Comment by admincheg** [comment]
This is screenshot from project, but I think this error doesn't related to one project.

![1606216146](https://user-images.githubusercontent.com/769936/100086603-8c83c880-2e45-11eb-8a1d-fd73f7391afe.png)

**Comment by untitaker** [comment]
Can you also go to Settings -> Projects -> (the project this is crashing on) -> Security & Privacy

**Comment by admincheg** [comment]
Some kind of information about our setup:

1. Our instance was updated from version 8 through 9.1.2 to 20.10.1
2. All services builded and installed to physical machine without dockerization

**Comment by untitaker** [comment]
Ok thanks, I was specifically looking for an enabled Use Default Scrubbers.

If you want a quick workaround, disabling this setting and restarting relay should fix it, at the expense of disabling data scrubbing.

I don't think I've seen this bug in production, and we really do have a lot of projects and events.

**Comment by untitaker** [comment]
actually @admincheg, the assertion is a `debug_assert!`. Did you compile Relay yourself? I think you missed the `--release` option when running `cargo build`.

**Comment by admincheg** [comment]
I was try to build your project through Makefile, but cargo told me wrong keyword `+stable` and as I see your variant isn't working too:

```
sentry@sentry4:/opt/relay$ cargo -V
cargo 1.42.1
sentry@sentry4:/opt/relay$ cargo build --all-features --stable
error: Found argument '--stable' which wasn't expected, or isn't valid in this context

USAGE:
    cargo build --all-features

For more information try --help
```

**Comment by admincheg** [comment]
Whoa, sorry, think about one thing, type another. With `--release` keyword building started, but Makefile didn't work.

**Comment by untitaker** [comment]
Yes most things in the readme and the makefile are for development. There is `make release` (also mentioned in the readme) but it assumes rust installed via rustup.

`+stable` is for instructing cargo to use a stable rust compiler. It probably would not work if you installed rust via apt.

**Comment by untitaker** [comment]
You should see a drastic performance increase with `--release` btw.

**Comment by admincheg** [comment]
New interesting errors after building release version.

```
Nov 24 11:27:46 sentry4.dev.zorg.sh relay[30965]: 2020-11-24T11:27:46Z [relay_server::actors::upstream] INFO: registering with upstream (http://127.0.0.1:9001/)
Nov 24 11:27:46 sentry4.dev.zorg.sh relay[30965]: 2020-11-24T11:27:46Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
Nov 24 11:27:46 sentry4.dev.zorg.sh relay[30965]:   caused by: IO error: Connection reset by peer (os error 104)
Nov 24 11:27:46 sentry4.dev.zorg.sh relay[30965]:   caused by: Connection reset by peer (os error 104)
Nov 24 11:27:48 sentry4.dev.zorg.sh relay[30965]: 2020-11-24T11:27:48Z [relay_server::actors::upstream] INFO: registering with upstream (http://127.0.0.1:9001/)
Nov 24 11:27:48 sentry4.dev.zorg.sh relay[30965]: 2020-11-24T11:27:48Z [relay_server::actors::upstream] ERROR: authentication encountered error: could not send request to upstream
Nov 24 11:27:48 sentry4.dev.zorg.sh relay[30965]:   caused by: IO error: Connection reset by peer (os error 104)
Nov 24 11:27:48 sentry4.dev.zorg.sh relay[30965]:   caused by: Connection reset by peer (os error 104)
Nov 24 11:27:51 sentry4.dev.zorg.sh relay[30965]: 2020-11-24T11:27:51Z [relay_server::actors::upstream] INFO: registering with upstream (http://127.0.0.1:9001/)
Nov 24 11:27:51 sentry4.dev.zorg.sh relay[30965]: 2020-11-24T11:27:51Z [relay_server::actors::upstream] INFO: relay successfully registered with upstream
```
Additional log from another parts of project
```
Nov 24 11:27:33 sentry4 systemd[1]: Stopping Sentry Relay Service...
Nov 24 11:27:43 sentry4 systemd[1]: sentry-relay.service: Succeeded.
Nov 24 11:27:43 sentry4 systemd[1]: Stopped Sentry Relay Service.
Nov 24 11:27:43 sentry4 systemd[1]: Started Sentry Relay Service.
Nov 24 11:27:43 sentry4 sentry[22714]: 127.0.0.1 - - [24/Nov/2020:11:27:43 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 970 "-" "actix-web/0.7.19"
Nov 24 11:27:43 sentry4 sentry[22714]: 127.0.0.1 - - [24/Nov/2020:11:27:43 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 970 "-" "actix-web/0.7.19"
Nov 24 11:27:44 sentry4 sentry[22714]: 127.0.0.1 - - [24/Nov/2020:11:27:44 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 970 "-" "actix-web/0.7.19"
Nov 24 11:27:46 sentry4 sentry[22714]: 127.0.0.1 - - [24/Nov/2020:11:27:46 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 970 "-" "actix-web/0.7.19"
Nov 24 11:27:48 sentry4 sentry[22714]: 127.0.0.1 - - [24/Nov/2020:11:27:48 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 970 "-" "actix-web/0.7.19"
Nov 24 11:27:51 sentry4 sentry[22714]: 127.0.0.1 - - [24/Nov/2020:11:27:51 +0000] "POST /api/0/relays/register/challenge/ HTTP/1.1" 200 970 "-" "actix-web/0.7.19"
Nov 24 11:27:51 sentry4 sentry[22714]: 127.0.0.1 - - [24/Nov/2020:11:27:51 +0000] "POST /api/0/relays/register/response/ HTTP/1.1" 200 565 "-" "actix-web/0.7.19"
```
I think this issue can be moved to pending, while I looking for problems. Thanks for advice.

**Comment by jan-auer** [comment]
Have you considered using our onpremise sentry setup? This looks like an issue in request handling on the sentry server side, potentially the web server is not fully up. Our docker-compose setup aims to simplify setting up all these services and make them talk to each other.

**Comment by untitaker** [comment]
so we have two bugs here:

* networking issues -- if this is actually a relay bug it may happen for ext relays
* invalid assertion -- I would like to keep it as we should be able to see this assertion failure in tests only. but if it happened in prod it would also affect ext relays
